
import __ASTRO_IMAGE_IMPORT_Z1QTKXX from "../../assets/activity-networks-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fcritical-path-analysis.md";
import __ASTRO_IMAGE_IMPORT_Ztx67G from "../../assets/activity-networks-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fcritical-path-analysis.md";
import __ASTRO_IMAGE_IMPORT_24VVRC from "../../assets/linear-programming-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Flinear-programming.md";
import __ASTRO_IMAGE_IMPORT_Z24ESM2 from "../../assets/linear-programming-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Flinear-programming.md";
import __ASTRO_IMAGE_IMPORT_Z195ACK from "../../assets/linear-programming-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Flinear-programming.md";
import __ASTRO_IMAGE_IMPORT_2iUGad from "../../../assets/activity-networks-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Falevel-furthermaths%2Fcritical-path-analysis.md";
import __ASTRO_IMAGE_IMPORT_18F92v from "../../../assets/activity-networks-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Falevel-furthermaths%2Fcritical-path-analysis.md";
import __ASTRO_IMAGE_IMPORT_Z1f0Lsn from "../../../assets/linear-programming-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Falevel-furthermaths%2Flinear-programming.md";
import __ASTRO_IMAGE_IMPORT_ZpPozw from "../../../assets/linear-programming-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Falevel-furthermaths%2Flinear-programming.md";
import __ASTRO_IMAGE_IMPORT_ojXik from "../../../assets/linear-programming-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Falevel-furthermaths%2Flinear-programming.md";
import __ASTRO_IMAGE_IMPORT_Z5mOFf from "../../../assets/activity-networks-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fmaths%2Fcritical-path-analysis.md";
import __ASTRO_IMAGE_IMPORT_Z12P9lq from "../../../assets/activity-networks-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fmaths%2Fcritical-path-analysis.md";
import __ASTRO_IMAGE_IMPORT_1pzSwp from "../../../assets/linear-programming-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fmaths%2Flinear-programming.md";
import __ASTRO_IMAGE_IMPORT_2wmJaA from "../../../assets/linear-programming-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fmaths%2Flinear-programming.md";
import __ASTRO_IMAGE_IMPORT_Z1r2y0a from "../../../assets/linear-programming-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fmaths%2Flinear-programming.md";
export default new Map([["../../assets/activity-networks-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fcritical-path-analysis.md", __ASTRO_IMAGE_IMPORT_Z1QTKXX], ["../../assets/activity-networks-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fcritical-path-analysis.md", __ASTRO_IMAGE_IMPORT_Ztx67G], ["../../assets/linear-programming-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Flinear-programming.md", __ASTRO_IMAGE_IMPORT_24VVRC], ["../../assets/linear-programming-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Flinear-programming.md", __ASTRO_IMAGE_IMPORT_Z24ESM2], ["../../assets/linear-programming-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Flinear-programming.md", __ASTRO_IMAGE_IMPORT_Z195ACK], ["../../../assets/activity-networks-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Falevel-furthermaths%2Fcritical-path-analysis.md", __ASTRO_IMAGE_IMPORT_2iUGad], ["../../../assets/activity-networks-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Falevel-furthermaths%2Fcritical-path-analysis.md", __ASTRO_IMAGE_IMPORT_18F92v], ["../../../assets/linear-programming-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Falevel-furthermaths%2Flinear-programming.md", __ASTRO_IMAGE_IMPORT_Z1f0Lsn], ["../../../assets/linear-programming-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Falevel-furthermaths%2Flinear-programming.md", __ASTRO_IMAGE_IMPORT_ZpPozw], ["../../../assets/linear-programming-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Falevel-furthermaths%2Flinear-programming.md", __ASTRO_IMAGE_IMPORT_ojXik], ["../../../assets/activity-networks-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fmaths%2Fcritical-path-analysis.md", __ASTRO_IMAGE_IMPORT_Z5mOFf], ["../../../assets/activity-networks-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fmaths%2Fcritical-path-analysis.md", __ASTRO_IMAGE_IMPORT_Z12P9lq], ["../../../assets/linear-programming-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fmaths%2Flinear-programming.md", __ASTRO_IMAGE_IMPORT_1pzSwp], ["../../../assets/linear-programming-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fmaths%2Flinear-programming.md", __ASTRO_IMAGE_IMPORT_2wmJaA], ["../../../assets/linear-programming-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fmaths%2Flinear-programming.md", __ASTRO_IMAGE_IMPORT_Z1r2y0a]]);
		